// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEjgo8Q8LFc6_FCVzg-vpLH2u1w-qoqHg',
    appId: '1:236467056703:web:33c6a3e6b7047c4af1c88a',
    messagingSenderId: '236467056703',
    projectId: 'todo-app-7cf62',
    authDomain: 'todo-app-7cf62.firebaseapp.com',
    storageBucket: 'todo-app-7cf62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOpMuer2CasZxDkzBrepEhG0to1EAO1cs',
    appId: '1:236467056703:android:6ffbba632f0316c0f1c88a',
    messagingSenderId: '236467056703',
    projectId: 'todo-app-7cf62',
    storageBucket: 'todo-app-7cf62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCil-KoLk0xPzHQeXGUC3eiS_pw37Z1Wno',
    appId: '1:236467056703:ios:78c641a5bc5667f6f1c88a',
    messagingSenderId: '236467056703',
    projectId: 'todo-app-7cf62',
    storageBucket: 'todo-app-7cf62.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEjgo8Q8LFc6_FCVzg-vpLH2u1w-qoqHg',
    appId: '1:236467056703:web:031415c4b04f11c2f1c88a',
    messagingSenderId: '236467056703',
    projectId: 'todo-app-7cf62',
    authDomain: 'todo-app-7cf62.firebaseapp.com',
    storageBucket: 'todo-app-7cf62.appspot.com',
  );
}
